- name: ansible-ec2
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars: #used for tasks, can exist in a seprate file
    keypair: ansiblekeypair # region specific, create first
    instance_type: t2.micro
    image: ami-0c6120f461d6b39e9 # region specific, Amazon linux2
    wait: yes
    group: ansible-ec2
    count: 1
    region: ap-southeast-2
    security_group: ansible-security-grp

  tasks:
    - name: Task 1 - Create my security group
      local_action:
        module: ec2_group
        name: '{{ security_group }}'
        description: Security Group for ansible ec2
        region: '{{ region }}'
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall
    - name: Task 2 Launch the new EC2 Instance
      local_action: ec2
        group={{ security_group }}
        instance_type={{ instance_type}}
        image={{ image }}
        wait=true
        region={{ region }}
        keypair={{ keypair }}
        count={{count}}
      register: ec2
    - name: Task 3 Add Tagging to EC2 instance
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: '{{ ec2.instances }}'
      args:
        tags:
          Name: dev-besu-*
          Version: 20.10.0
          Owner: Bobby Fisher
